version: '3.1'

services:
  imdb_mongo_server:
    image: bialkowskisz/imdb_mongo:latest
    build: ./imdb_mongo

  python_api:
    image: bialkowskisz/python_api:latest
    build: ./python_api
    ports:
      - '5000:80'
    depends_on:
      - imdb_mongo_server
